index.d.ts: export top level Settings declaration
This was causing issues when using the 0.3.x branch in a typescript context

```
../planck.js/lib/index.d.ts:539:1 - error TS1046: Top-level declarations in \
.d.ts files must start with either a 'declare' or 'export' modifier.

539 let Settings: {
    ~~~
```